#!/usr/bin/env python3
"""
Klaviyo Configuration for Alpha Medical Care Store
Reconnect Klaviyo from Hendersonshop to Alpha Medical (azffej-as.myshopify.com)

CRITICAL: This script documents the manual reconfiguration steps needed
"""

import os
import json
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

KLAVIYO_PUBLIC_KEY = os.getenv('KLAVIYO_PUBLIC_API_KEY')  # pk_b51a04697c36bd77b65c3376e1f0409621
SHOPIFY_STORE = os.getenv('SHOPIFY_STORE_DOMAIN')  # azffej-as.myshopify.com

print("="*80)
print("KLAVIYO RECONFIGURATION GUIDE - Alpha Medical Care")
print("="*80)
print()

print("CURRENT STATUS:")
print(f"  ❌ Klaviyo connected to: Hendersonshop (WRONG)")
print(f"  ✅ Correct store: {SHOPIFY_STORE}")
print(f"  ✅ Public API Key: {KLAVIYO_PUBLIC_KEY[:20]}...")
print()

print("="*80)
print("MANUAL RECONFIGURATION STEPS (30-45 min)")
print("="*80)
print()

print("STEP 1: ACCESS KLAVIYO DASHBOARD")
print("-" * 40)
print("1. Go to https://www.klaviyo.com/login")
print("2. Log in with your Klaviyo account")
print("3. You should see 'Hendersonshop' as current account")
print()

print("STEP 2: DISCONNECT FROM HENDERSONSHOP")
print("-" * 40)
print("1. Click 'Integrations' in left sidebar")
print("2. Find 'Shopify' integration")
print("3. Click 'Settings' or '...' menu")
print("4. Click 'Disconnect' or 'Remove integration'")
print("5. Confirm disconnection")
print()

print("STEP 3: CONNECT TO ALPHA MEDICAL STORE")
print("-" * 40)
print("1. Still in 'Integrations' page")
print("2. Click 'Add Integration' or 'Connect' for Shopify")
print("3. Enter your Shopify store URL:")
print(f"   → {SHOPIFY_STORE}")
print("4. Click 'Connect to Shopify'")
print("5. You'll be redirected to Shopify admin")
print("6. Review permissions requested by Klaviyo:")
print("   - Read/write customers")
print("   - Read orders")
print("   - Read products")
print("   - Write checkouts")
print("7. Click 'Install app' or 'Authorize'")
print()

print("STEP 4: VERIFY CONNECTION")
print("-" * 40)
print("1. Return to Klaviyo dashboard")
print("2. Verify 'Shopify' shows as 'Connected'")
print(f"3. Verify store name shows: {SHOPIFY_STORE}")
print("4. Check 'Integration Health' - should be green")
print()

print("STEP 5: CONFIGURE TRACKING")
print("-" * 40)
print("1. In Klaviyo → Settings → Tracking")
print("2. Enable 'Shopify Integration Tracking':")
print("   ✓ Viewed Product")
print("   ✓ Added to Cart")
print("   ✓ Started Checkout")
print("   ✓ Placed Order")
print("   ✓ Fulfilled Order")
print("3. Verify API key matches:")
print(f"   Public Key: {KLAVIYO_PUBLIC_KEY}")
print()

print("STEP 6: CREATE WELCOME FLOW (Pain Relief Guide)")
print("-" * 40)
print("1. In Klaviyo → Flows → Create Flow")
print("2. Name: 'Pain Relief Guide Delivery'")
print("3. Trigger: 'Added to List' → Tag 'pain-relief-guide-download'")
print("4. Add Email:")
print("   Subject: 'Your FREE Pain Relief Guide is Ready 📥'")
print("   Preview: 'Download your complete guide to pain relief...'")
print("5. Email content:")
print("   - Greeting: Hi {{ person.first_name|default:'there' }}")
print("   - Download button with PDF URL:")
print("     Upload PDF to Shopify Files first:")
print("     → Shopify Admin → Settings → Files → Upload")
print("     → Copy URL: https://cdn.shopify.com/s/files/.../Ultimate_Pain_Relief_Guide.pdf")
print("   - Value reinforcement")
print("   - Support contact")
print("6. Set timing: Send immediately (0 minutes delay)")
print("7. Save and activate flow")
print()

print("STEP 7: CREATE ABANDONED CART FLOW")
print("-" * 40)
print("1. In Klaviyo → Flows → Create Flow")
print("2. Use template: 'Abandoned Cart Flow'")
print("3. Customize trigger: 'Added to Cart' + 'Has not ordered since starting this flow'")
print("4. Email 1 (1 hour delay):")
print("   Subject: 'Complete your order - Alpha Medical Care'")
print("   Content: Product reminder, urgency, free shipping")
print("5. Email 2 (24 hours delay - OPTIONAL):")
print("   Subject: 'Still thinking it over?'")
print("   Content: Product benefits, customer reviews")
print("6. Email 3 (48 hours delay - OPTIONAL):")
print("   Subject: 'Last chance: 10% off your cart'")
print("   Content: Exclusive discount code")
print("7. Save and activate flow")
print()

print("STEP 8: UPDATE LANDING PAGE FORM")
print("-" * 40)
print("1. In Klaviyo → Lists & Segments")
print("2. Create list: 'Pain Relief Guide Subscribers'")
print("3. Add tag: 'pain-relief-guide-download'")
print("4. Go to Forms → Create Form → Embedded Form")
print("5. Design form fields:")
print("   - Email (required)")
print("   - First Name (optional)")
print("6. Set form to add to 'Pain Relief Guide Subscribers' list")
print("7. Copy embed code")
print("8. Replace HTML form in pain-relief-guide page with Klaviyo embed")
print()

print("STEP 9: TEST EVERYTHING")
print("-" * 40)
print("1. Submit test email on pain-relief-guide landing page")
print("2. Check Klaviyo dashboard → People → Find your test email")
print("3. Verify:")
print("   ✓ Email appears in 'Pain Relief Guide Subscribers' list")
print("   ✓ Welcome email sent immediately")
print("   ✓ PDF download link works")
print("4. Test abandoned cart:")
print("   a. Add product to cart")
print("   b. Start checkout (enter email)")
print("   c. Abandon without completing")
print("   d. Wait 1 hour")
print("   e. Check inbox for abandoned cart email")
print()

print("STEP 10: MONITOR PERFORMANCE")
print("-" * 40)
print("1. Klaviyo Dashboard → Analytics")
print("2. Track metrics:")
print("   - Email list growth rate (target: +200/month)")
print("   - Welcome flow open rate (target: >50%)")
print("   - Welcome flow click rate (target: >20%)")
print("   - Abandoned cart recovery rate (target: 5-8%)")
print("3. Weekly review and optimization")
print()

print("="*80)
print("EXPECTED IMPACT")
print("="*80)
print()
print("✅ Email List Growth: +200-300 subscribers/month")
print("✅ Welcome Flow: 50%+ open rate, 20%+ click rate")
print("✅ Abandoned Cart Recovery: 5-8% conversion rate")
print("✅ Additional Revenue: $500-800/month")
print("✅ Customer Engagement: Automated nurturing")
print()

print("="*80)
print("IMPORTANT NOTES")
print("="*80)
print()
print("⚠️  This is MANUAL configuration - no automation possible")
print("⚠️  Estimated time: 30-45 minutes")
print("⚠️  Klaviyo Free Plan: Up to 250 contacts")
print("⚠️  After 250 contacts, paid plans start at $20/month")
print("⚠️  Test thoroughly before going live")
print()

print("="*80)
print("FILES TO UPDATE AFTER CONFIGURATION")
print("="*80)
print()
print("1. Update .env with Klaviyo Private API Key (if needed for backend):")
print("   KLAVIYO_PRIVATE_API_KEY=your_private_key_here")
print()
print("2. Update pain-relief-guide landing page:")
print("   - Replace HTML form with Klaviyo embed code")
print()
print("3. Document in SEO_MARKETING_FORENSIC_ANALYSIS.md:")
print("   - Klaviyo reconnection complete")
print("   - Flows activated (Welcome + Abandoned Cart)")
print("   - Expected metrics")
print()

print("CONFIGURATION GUIDE GENERATED SUCCESSFULLY!")
print()
